"""add table bet

Revision ID: 1ab90e07d2e8
Revises: ba6942c49867
Create Date: 2025-02-22 01:01:33.252164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ab90e07d2e8'
down_revision: Union[str, None] = 'ba6942c49867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('expected_amount', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('NOT_PLAY', 'WON', 'LOST', name='bet_status'), server_default=sa.text("'NOT_PLAY'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    # ### end Alembic commands ###
